---
- name: copy zookeeper-rpm
  copy: src=zookeeper-3.4.6.tar.gz dest=/opt

- name: install zookeeper
  - command: cd /opt & tar -zxvf zookeeper-3.4.6.tar.gz & cd zookeeper-3.4.6

- template: >
    src=zoo.cfg.j2
    dest=/opt/zookeeper-3.4.6/conf/zoo.cfg
    mode=666

- name: configure Zookeeper myid
  template: src=myid.j2 dest=/opt/zookeeper-3.4.6/zkdata/myid
