---
- name: copy zookeeper data
  copy: src=zookeeper-3.4.6.tar.gz dest=/opt

- name: install zookeeper
  - command: cd /opt ; tar -zxvf /opt/zookeeper-3.4.6.tar.gz

- template: >
    src=zoo.cfg.j2
    dest=/opt/zookeeper-3.4.6/conf/zoo.cfg
    mode=666