---
- name: install zookeeper
  remote_user: ubuntu
  hosts: zookeeper
  sudo: yes
  roles:
    - pangu-zookeeper


- name: install storm
  remote_user: ubuntu
  hosts: storm
  sudo: yes
  roles:
   - pangu-storm