---
- name: copy storm
  copy: src=apache-storm-0.9.5.tar.gz dest=/opt

- name: install storm
  shell: cd /opt ; tar -zxvf apache-storm-0.9.5.tar.gz

- file: path=/opt/apache-storm-0.9.4/data state=directory mode="u=rwx,g=rx,o=rx"


- template: >
    src=storm.yaml.j2
    dest=/opt/apache-storm-0.9.5/conf/storm.yaml
    mode=666
