---
- name: copy storm-rpm
  copy: src=x86_64/apache-storm-0.9.4-1.x86_64.rpm dest=/opt

- name: install storm
  yum: name=/opt/apache-storm-0.9.4-1.x86_64.rpm state=present

- file: path=/opt/apache-storm-0.9.4/data state=directory mode="u=rwx,g=rx,o=rx"

- name: add hostname
  lineinfile: dest=/etc/hosts
              line="{{ hostvars[item]['ansible_ssh_host'] }} {{item}}"
  with_items: groups['storm']

- template: >
    src=storm.yaml.j2
    dest=/opt/apache-storm-0.9.4/conf/storm.yaml
    mode=666
