---
- name: copy storm
  copy: src=apache-storm-0.9.5.tar.gz dest=/opt

- name: install storm
  shell: cd /opt ; tar -zxvf apache-storm-0.9.5.tar.gz

- file: path=/opt/apache-storm-0.9.4/data state=directory mode="u=rwx,g=rx,o=rx"

- name: add hostname
  lineinfile: dest=/etc/hosts
              line="{{ hostvars[item]['ansible_ssh_host'] }} {{item}}"
  with_items: groups['storm']

- template: >
    src=storm.yaml.j2
    dest=/opt/apache-storm-0.9.4/conf/storm.yaml
    mode=666
