---
 - name: Enable 38286
   firewalld: port=38286/tcp permanent=true state=enabled
   notify: Restart firewalld

 - name: Enable 6700
   firewalld: port=6700/tcp permanent=true state=enabled
   notify: Restart firewalld

 - name: Enable 6701
   firewalld: port=6701/tcp permanent=true state=enabled
   notify: Restart firewalld

 - name: Enable 6702
   firewalld: port=6702/tcp permanent=true state=enabled
   notify: Restart firewalld

 - name: Enable 6703
   firewalld: port=6703/tcp permanent=true state=enabled
   notify: Restart firewalld
