---
- name: install the EPEL repository
  apt_repository: repo='ppa:webupd8team/java'

- name: install java7-installer
  apt: name=oracle-java7-installer state=present

- name: install java7-set-default
  apt: name=oracle-java7-set-default state=present
